### ISSUE TITLE
Support token DSL in synonyms definitions. 

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#113]
We need to able to use found tokens (i.e. token or found elements) in synonyms definitions:

1. I think instead of just using element/token ID we should use the syntax/capability from intent DSL, i.e. 

```
{nice|cool ~~~group @@ 'geo' && ~GEO_KIND == 'CITY'~~~}
{avg|average ~~~id == 'user:ner' && ~ELEM_TYPE == 'NUM'~~~}
```

This way it's more powerful and it reuses the same syntax from intent DSL (shorter learning curve).

2. We need to expand `NCCustomerParser` to make it more flexible. Need to think through the specific extensions.
3. We need to have a list of `NCCustomParsers` instead of just one like we have right now.
4. As far as function enricher - I'd wait till this refactoring is done and see if it "survives".

**Comment by skhdl** [comment]
first part ready for review тв discuss (See TODO list)

**Comment by vic64** [comment]
Code review comments:
1. The common methods in `NCCustomWord` and `NCToken` interfaces should be abstracted out to a common super-interface (`NCNlpChunk`). Currently, the same methods are named differently and some methods are missings in `NCCustomWord`.

**Comment by skhdl** [comment]
Look at changes related to NCCustomWord and NCToken in GH-113

**Comment by vic64** [comment]
Good to merge to release.
