### ISSUE TITLE
Why "nlpcraft:geo" tokens have weight and are treated specially by intent matcher?

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#129]
NCIntentSolverVariant#79

We should have a universal approach: either all tokens can have weight or none.

**Comment by skhdl** [comment]
fixed in GH-129 (based on GH-113)

**Comment by skhdl** [comment]
GH-129 is based on GH-133
It contains changes for 129 and 46 tickets

If it seems ok, it should be merged to 113 as soon as possible

**Comment by skhdl** [comment]
Geo description in GH-46

**Comment by skhdl** [comment]
Merged into GH-113
