### ISSUE TITLE
org.nlpcraft.server.rest.NCBasicRestApi `rmtAddr` of ask methods.

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#138]
It is detected as like rmtAddr=0:0:0:0:0:0:0:1:63094
Further is provided as remoted addresses, and it is the cause of error in Weather example.

**Comment by vic64** [comment]
Is this fixed by GH-136?

**Comment by skhdl** [comment]
Look at GH-138 branch, please
I am not sure that is is best solution, maybe better to check via java.net.InetAddress#isLoopbackAddress method
