### ISSUE TITLE
Support for onBehalfOf for /ask REST calls.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#143]
Notes:
- need to add an `ext_id` field for user table
- support `onBehalfOf` or `extId` parameter on `/ask` REST calls (including test clients and Java native client).

**Comment by skhdl** [comment]
ready for review in GH-143

**Comment by vic64** [comment]
Core review comments:
- /user/get should support 'admin' mode where an admin get information about any user in the same company.

**Comment by skhdl** [comment]
1) >>
    /company/get should support 'usrExtId' as well
Do you mean "/user/get"?

2) NCUser result changed (for user/all, user/get)
 - added properties (was missed)
 - deleted companyId (we don't need it)

3) /check and /ask/sync result changed - deleted state createTimestamp and updateTimestamp
(too difficult to support for embedded mode, also it is not so necessary, we have tracing etc)

4) added 2 fields to NCEmbeddedResult (getProbeId, getLogHolder)

5) client fixed
