### ISSUE TITLE
Remove context enricher and move logic into corresponding enrichers.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#145]
Right now, the context enricher is responsible for marking some surrounding words around geo/num/function tokens as stopwords. This logic should be moved into target geo/num/function enrichers instead.

**Comment by skhdl** [comment]
1) delete NCContextEnricher
2) delete NCPostEnricher
3) NCPostEnrichCollapser.collapse should be called once

**Comment by skhdl** [comment]
ready for review GH-145-1
