### ISSUE TITLE
Weather example doesn't work (See tests)

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#156]

**Comment by vic64** [comment]
There's no branch GH-156.

**Comment by skhdl** [comment]
![изображение](https://user-images.githubusercontent.com/6073674/68549054-fbda7600-0404-11ea-9c31-f96824bd31d8.png)

**Comment by skhdl** [comment]
The sentence `What's the local weather forecast?` failed with 
following check isAmbiguousMatch() (It is true)
So please 
 - fix `isAmbiguousMatch` logic or
 - change example if new logic behaviour is ok

**Comment by vic64** [comment]
I've made the fix in `release` for ambiguous logic but the example still doesn't work.

**Comment by skhdl** [comment]
fixed in GH-145-1
(Weather model was refactored with indexes usage mistakes)
