### ISSUE TITLE
Refactor probe.mgr.nlp.impl package.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#158]
1. This package has only one real 'impl' class (used only by one another class).
2. It has another class that has nothing to do with 'impl' (just there for a shared place).

Likely needs to be removed and its classes moved to more appropriate places.

**Comment by skhdl** [comment]
fixed in GH-145-1

**Comment by vic64** [comment]
What's fixed? The package remains unchanged.
