### ISSUE TITLE
Probe starts if some model broken

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#165]
![изображение](https://user-images.githubusercontent.com/6073674/69433263-57352e00-0d4c-11ea-9a73-e6a3ecd6273a.png)
![изображение](https://user-images.githubusercontent.com/6073674/69433280-60be9600-0d4c-11ea-84a0-4d4bd0c24881.png)

**Comment by vic64** [comment]
Fixed in `release`.
