### ISSUE TITLE
NCTokenImpl shortcut methods 

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#169]
1) Do we need them?
    override lazy val getMetadata: NCMetadata = meta
    override lazy val getServerRequestId: String = srvReqId
    override lazy val getId: String = id
    override lazy val getGroups: java.util.List[String] = grps.asJava
    override lazy val getParentId: String = parentId
    override lazy val getAncestors: java.util.List[String] = ancestors.asJava
    override lazy val getValue: String = value
    override lazy val getStartCharIndex: Int = startCharIndex
    override lazy val getEndCharIndex: Int = endCharIndex
    override lazy val isUserDefined: Boolean = !sys
    override lazy val isSystemDefined: Boolean = sys
    override lazy val isFreeWord: Boolean = get("freeword")
    override lazy val getUnid: String = get("unid")
    override lazy val isStopWord: Boolean = get("stopword")
    override lazy val isSwearWord: Boolean = get("swear")
    override lazy val getSparsity: Int = get("sparsity")
    override lazy val getMinIndex: Int = get("minindex")
    override lazy val isDirectSynonym: Boolean = get("direct")
    override lazy val getMaxIndex: Int = get("maxindex")
    override lazy val getWordLength: Int = get("wordlength")
    override lazy val isContiguous: Boolean = get("contiguous")
    override lazy val isEnglish: Boolean = get("english")
    override lazy val getWordIndexes: util.List[Integer] = get("wordindexes")
    override lazy val isBracketed: Boolean = get("bracketed")
    override lazy val getPosDescription: String = get("posdesc")
    override lazy val isKnownWord: Boolean = get("dict")
    override lazy val getTokenIndex: Int = get("index")
    override lazy val getLemma: String = get("lemma")
    override lazy val getStem: String = get("stem")
    override lazy val getCharLength: Int = get("charlength")
    override lazy val getOriginalText: String = get("origtext")
    override lazy val getNormalizedText: String = get("normtext")
    override lazy val getPos: String = get("pos")
    override lazy val isQuoted: Boolean = get("quoted")

2) Aftewr fixes, check output of EchoExample.

**Comment by vic64** [comment]
Fixed in `release`.
