### ISSUE TITLE
Support dynamic value loading in JSON/YAML model definitions.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#186]
Need to introduce "valueLoader" to JSON/YAML format. It should contain a fully qualified class name for the loader that will be called during model instantiation to load the values for the given element.

Need to introduce `NCValueLoader` interface as well.

**Comment by skhdl** [comment]
GH-186
not tested, it will be tested with SQL example (we can do it without new version, locally installing vai maven)

**Comment by vic64** [comment]
I think you need to pass element metadata as well (additionally to element ID).

**Comment by vic64** [comment]
Made the change.
