### ISSUE TITLE
NCDslTokenPredicate uses nullable values incorrectly 

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#188]
1) org.nlpcraft.model.impl.NCTokenImpl - 
srvReqId, id, grps, ancestors, meta not null
but parentId and value are nullable
2) NCDslTokenPredicate line 310 (at least this place, we have to check everywhere)
                case "value":  lval = tok.getValue().trim(); break;
                case "parent": lval = tok.getParentId().trim(); break;

So we have NPE when using `value` and `parentId` in DSL

**Comment by vic64** [comment]
Fixed in GH-185.
