### ISSUE TITLE
SQL model generator must support --override flag.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#189]

**Comment by vic64** [comment]
See https://github.com/google/diff-match-patch for the library to use.

**Comment by vic64** [comment]
To support this, we should introduce a new parameter: [--merge|-m] [true|false]

If the output file already exists and --merge is true, then the delta between new and old generated models gets applied to the old file (i.e. performing a merge). If --merge is false or file doesn't already exist - the new file overrides the old one.

**Comment by skhdl** [comment]
ready for review GH-189 (case "--override" | "-z" . "-x" is used by --model-id
