### ISSUE TITLE
NCModelJson errors

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#193]
field name is org.nlpcraft.model.impl.json.NCModelJson#usrMetadata
method name is org.nlpcraft.model.impl.json.NCModelJson#getUserMetadata

in JSON:
usrMetadata works
userMetadata doesn't 

So, usrMetadata should be renamed to usrMetadata (+ related chanhes in generetor should be taken into account)

private Map<String, Serializable> usrMetadata; - It doesn't work for 
    "userMetadata": {
        "sql:url": "jdbc:h2:mem:default;INIT=RUNSCRIPT FROM 'classpath:northwind.sql'",
        "sql:driver": "org.h2.Driver",
        "sql:output": "nlp2SqlModel.json",
        "sql:timestamp": "2020-01-12T19:40:30.078Z" // ,
//        "references": [
//            {
//                "fromTable": "orders",
//                "fromColumns": ["customer_id"],
//                "toTable": "customers",
//                "toColumns": ["customer_id"]
//            }
//        ]
    },

See commented block.

**Comment by vic64** [comment]
Fixed in GH-190. Note that the correct name is 'metadata'.

**Comment by skhdl** [comment]
It doesn't work
To reproduce - start probe in GH-190
Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: java.io.Serializable
