### ISSUE TITLE
Multiple elements should be able to have the same synonym (resolved via variants).

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#198]

**Comment by skhdl** [comment]
Hmm. The system already allows having one synonym for different elements. (It worsk correct and finds all elements)
So 
 - We have to fix GH-195
 - Maybe we can keep but a little bit change warning text
Jan-21|15:19:14|WARN | Duplicate synonym stem detected [model=sql.model.id, element=(id=col:us_states.state_abbr, value=AK,id=col:customers.region, value=AK), synonym=(AK|TEXT)]

**Comment by skhdl** [comment]
Additionally
I am not sure that these warnings are printed when one synonym is stood for **different** elements (I guess we should)

**Comment by vic64** [comment]
Fixed in `release`.
