### ISSUE TITLE
'OR' support for nested elements DSL

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#202]
- `^^^id  == 'element:column' && (~sql:dataType == 4 || ~sql:dataType == 8)^^^` doesn't work
 - `^^^id  == 'element:column' && (~sql:dataType == 4 \\|\\| ~sql:dataType == 8)^^^` works, but it is not convenient.

**Comment by vic64** [comment]
Fixed in GH-202.
