### ISSUE TITLE
`EnabledTokens` configuration.

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#204]
1) we have to configure the `enabled-tokens` list, for tokens which can be used for nested tokens.
2) but also we need to configure the second list, for result tokens which can be used in variants.

How it can be configured user-friendly?

Note that current implementation supports only nlpcraft, google etc tokens in the enabled list, and doesn't allow to add user tokens here.

**Comment by vic64** [comment]
Agreed to simply rename this to "enabledBuiltInTokens" and add onToken callback.
