### ISSUE TITLE
We need the way to access to part tokens from DSL

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#205]

**Comment by vic64** [comment]
How about this proposal:

```^^^~meta == 'foo'^^^``` 
- refers to the metadata of the current token (_current implementation_).

```^^^'id1'.~meta == 'foo'^^^``` 
- refers to the metadata of the part token with ID 'id1' of the current token.

```^^^'id1'(2).~meta == 'foo'^^^``` 
- refers to the metadata of the 3rd part token with ID 'id1' of the current token.

```^^^'id1'.'id2'(1)~meta == 'foo'^^^``` 
- refers to the metadata of the 2nd part token with ID 'id2' of the part token with ID 'id2' of the current token.

**Comment by vic64** [comment]
The better idea is to use tags/aliases:
```^^^[tag]~meta == 'foo'^^^```

and then:
```^^^id1.tag.~meta == 'bar'^^^```
