### ISSUE TITLE
Add acceptToken(Tok) callback to NCModel.

### ISSUE THREAD

**Issue by vic64** [nlpcrafters/nlpcraft#207]

**Comment by vic64** [comment]
I've added a callback ```acceptToken(...)``` on the ```NCModel``` and updated the documentation. You need to add a call site for this callback.

**Comment by skhdl** [comment]
There aren't GH-207 branches.

**Comment by vic64** [comment]
Create one from release.

**Comment by skhdl** [comment]
All preliminary work should be dropped according to the last meeting.

**Comment by vic64** [comment]
Fixed in `release` branch.
