### ISSUE TITLE
NCElement should have access to metadata values via methods similar to org.nlpcraft.model.NCToken#meta(String)

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#219]

**Comment by vic64** [comment]
Fixed in GH-219. See also `NCToken#findPartTokens(...)` method for more sophisticated part token search.

**Comment by skhdl** [comment]
- NCToken is Serializable, but
 - NCMetadata is not Serializable and provides Map<String, **Object**> getMetadata();
Is it correct?
