### ISSUE TITLE
SQL generator extension

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#220]
1) for each table add meta List[String] "selectList" .
It is used as a default select columns list for the configured table.
Default value - the first 3 columns should be added. 

2) for each table add meta List[(String, Boolean)]"orderBy" 
It is used as a default order_by list (columns and `asc` flag) for the configured table.
Default value - List(PK, false)

**Comment by vic64** [comment]
```
  metadata:
    sql:defaultselect:
    - "shipper_id"
    - "company_name"
    - "phone"
    sql:defaultsort:
    - "shipper_id#asc"
```

**Comment by vic64** [comment]
Fixed in GH-220 branch.
