### ISSUE TITLE
We should extend 'nlp:geo' with more demographic information. 

### ISSUE THREAD

**Issue by aradzinski** [nlpcrafters/nlpcraft#46]
We should extend both COUNTRY and CITY types (as much as possible in a limited time) based on the publicly available lists. 

For example:
- Capital city for the country
- Population, density, general coordinate
- Area
- May be some growth metrics

**Comment by skhdl** [comment]
Also, we should use this info when calculating 'weight' of note.

**Comment by skhdl** [comment]
please select preferable metrics

1) countries


#ISO	
ISO3	
ISO-Numeric	
fips	
Country	
Capital	
Area(in sq km)	
Population	
Continent	
tld	
CurrencyCode	
CurrencyName	
Phone	
Postal 
Code 
Format	
Postal Code 
Regex	
Languages	
geonameid	
neighbours	
EquivalentFipsCode

examples:

AD	AND	020	AN	Andorra	Andorra la Vella	468	84000	EU	.ad	EUR	Euro	376	AD###	^(?:AD)*(\d{3})$	ca	3041565	ES,FR	
AE	ARE	784	AE	United Arab Emirates	Abu Dhabi	82880	4975593	AS	.ae	AED	Dirham	971			ar-AE,fa,en,hi,ur	290557	SA,OM	


2) biggest cities

geonameid         : integer id of record in geonames database
name              : name of geographical point (utf8) varchar(200)
asciiname         : name of geographical point in plain ascii characters, varchar(200)
alternatenames    : alternatenames, comma separated, ascii names automatically transliterated, convenience attribute from alternatename table, varchar(10000)
latitude          : latitude in decimal degrees (wgs84)
longitude         : longitude in decimal degrees (wgs84)
feature class     : see http://www.geonames.org/export/codes.html, char(1)
feature code      : see http://www.geonames.org/export/codes.html, varchar(10)
country code      : ISO-3166 2-letter country code, 2 characters
cc2               : alternate country codes, comma separated, ISO-3166 2-letter country code, 200 characters
admin1 code       : fipscode (subject to change to iso code), see exceptions below, see file admin1Codes.txt for display names of this code; varchar(20)
admin2 code       : code for the second administrative division, a county in the US, see file admin2Codes.txt; varchar(80) 
admin3 code       : code for third level administrative division, varchar(20)
admin4 code       : code for fourth level administrative division, varchar(20)
population        : bigint (8 byte int) 
elevation         : in meters, integer
dem               : digital elevation model, srtm3 or gtopo30, average elevation of 3''x3'' (ca 90mx90m) or 30''x30'' (ca 900mx900m) area in meters, integer. srtm processed by cgiar/ciat.
timezone          : the iana timezone id (see file timeZone.txt) varchar(40)
modification date : date of last modification in yyyy-MM-dd format

examples:
3039163	Sant Julià de Lòria	Sant Julia de Loria	San Julia,San Julià,Sant Julia de Loria,Sant Julià de Lòria,Sant-Zhulija-de-Lorija,sheng hu li ya-de luo li ya,Сант-Жулия-де-Лория,サン・ジュリア・デ・ロリア教区,圣胡利娅-德洛里亚,圣胡利娅－德洛里亚	42.46372	1.49129	P	PPLA	AD		06				8022		921	Europe/Andorra	2013-11-23
3039678	Ordino	Ordino	Ordino,ao er di nuo,orudino jiao qu,Ордино,オルディノ教区,奥尔迪诺	42.55623	1.53319	P	PPLA	AD		05				3066		1296	Europe/Andorra	2009-12-11
3040051	les Escaldes	les Escaldes	Ehskal'des-Ehndzhordani,Escaldes,Escaldes-Engordany,Les Escaldes,esukarudesu=engorudani jiao qu,lai sai si ka er de-en ge er da,Эскальдес-Энджордани,エスカルデス＝エンゴルダニ教区,萊塞斯卡爾德-恩戈爾達,萊塞斯卡爾德－恩戈爾達	42.50729	1.53414	P	PPLA	AD		08				15853		1033	Europe/Andorra	2008-10-15

**Comment by skhdl** [comment]
1) deleted city Latitude/Longitude properties
2) deleted org.nlpcraft.model.utils.NCTokenUtils#getGeoLatitude / getGeoLongitude
3) added 
 - cityMeta (for geo tokens with kind CITY) and 
 - countryMeta (for geo tokens with kind CITY and COUNTRY)
4) added org.nlpcraft.model.utils.NCTokenUtils#getGeoCountryMeta, getGeoCityMeta



countryMeta and cityMeta -  Map[String, String]

country fields: (all fields represented as strings)
        name: String,
        iso: String,
        iso3: String,
        code: String,
        capital: Option[String],
        area: Option[Double],
        population: Option[Long],
        continent: String,
        currencyCode: Option[String],
        currencyName: Option[String],
        phone: Option[String],
        postalCodeFormat: Option[String],
        postalCodeRegex: Option[String],
        languages: Option[String], (comma separated list)
        neighbours: Option[String], (comma separated list)
        regions: Seq[JsonRegion] (comma separated list)

http://download.geonames.org/export/dump/countryInfo.txt   

Examples:

all data http://download.geonames.org/export/dump/countryInfo.txt and desc

"GEO_COUNTRYMETA": 
 "Map(iso3 -> fra, area -> 547030.0, population -> 64768389, continent -> eu, iso -> fr, isoCode -> 250, languages -> fr-fr,frp,br,co,ca,eu,oc, capital -> paris, neighbours -> ch,de,be,lu,it,ad,mc,es, phone -> 33)",

     

city fields: (all fields represented as strings)
        - name: String,  (name of geographical point )
        - latitude: Double, (latitude in decimal degrees (wgs84))
        - longitude: Double, (longitude in decimal degrees (wgs84))
        - population: Long, (bigint (8 byte int) )
        - elevation: Option[Int], (in meters, integer)
        - dem: Int, (digital elevation model, srtm3 or gtopo30, average elevation of 3''x3'' 
        	  (ca 90mx90m) or 30''x30'' (ca 900mx900m) area in meters, integer. srtm processed by cgiar/ciat.)
        - timezone: String (the iana timezone id (see file timeZone.txt) varchar(40))

(http://download.geonames.org/export/dump/ See The main 'geoname' table has the following fields :)


Examples:

"GEO_CITYMETA": 
"Map(latitude -> 48.85341, population -> 2138551, timezone -> europe/paris, dem -> 42, longitude -> 2.3488)",


 Added to geo country

**Comment by vic64** [comment]
Can you update this together with 'nlpcraft:geo' rework so that we can review & close both?

**Comment by skhdl** [comment]
Merged into GH-129

**Comment by skhdl** [comment]
Merged into GH-113

**Comment by vic64** [comment]
Looks good as part of GH-113.
